spring.application.name=sistema-de-avaliacao-de-lugares
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/places_db
spring.datasource.username=postgres
spring.datasource.password=saopaulomorumbi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
